FROM tensorflow/tensorflow:2.5.1-gpu
WORKDIR /app
ADD ./requirements.txt requirements.txt
RUN pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --proxy http://192.168.1.116:7890/
ADD . /app
EXPOSE 8080
CMD ["python","/app/main.py"]

